### ISSUE TITLE
regarding using the image on arbitary pages

### ISSUE THREAD

**Issue by gargsp123** [githubharald/WordDetector#5]
Hello,as mentioned in readme,words should have height in the range of 25-50 pixels.So I am assuming that before feeding the image,it needs to be resized.Any ideas on how to do this.For example:
This is from IAM Bern and unfortunately using the current settings the algo fails
It also fails if I crop a line from my page and feed it.
The line img . page image and the output is enclosed.
![6](https://user-images.githubusercontent.com/86523189/131207905-a3b8da62-cb48-4e4d-b70c-c976d38db3e3.png)
![a01-000x](https://user-images.githubusercontent.com/86523189/131207909-617316eb-9103-4e08-9fde-e4086bd2d28c.png)
![line_output](https://user-images.githubusercontent.com/86523189/131208282-ca1b25d9-104b-4db4-9c79-2e835097b9ae.png)

**Comment by githubharald** [comment]
Hi, 
the height of a text line should be ~50 pixel. So, you should determine to which height the page must be resized so that the text lines in it have ~50 pixel height. In your example, this is approximately 2000 pixels.
The following command gives these word detections for your image:
````python main.py  --data path/to/image.png --img_height 2000 --theta 5````

![Figure_1](https://user-images.githubusercontent.com/15148095/131255987-bf25a139-a8b8-479e-bb50-c17c07a817bb.png)
